%% Single-Phase PWM Inverter
%
% This example shows the operation of a single-phase PWM inverter.

% Copyright 2016 Hydro-Quebec, and The MathWorks, Inc.

%%

open_system('SinglePhasePWMInverter')

%% Description
%
% The system consists of two independent circuits illustrating single-phase PWM voltage-sourced inverters.
% 
% The Half-Bridge Converter block and the Full-Bridge converter block are modeling simplified model 
% of an IGBT/Diode pair where the forward voltages of the forced-commutated device and diode are ignored. 
%
% The converters are controlled in open loop with the PWM Generator blocks.
% The two circuits use the same DC voltage (Vdc = 400V), carrier frequency (1620 Hz) and modulation index (m = 0.8).
% 
% In order to allow further signal processing, signals displayed on the Scope block are stored in a variable named ScopeDataForFFT, in structure with time format.
% 
%
%% Simulation
%
% Run the simulation and observe the current into the loads and the voltage generated by the PWM inverters. 
%
% Once the simulation is completed, open the Powergui and select FFT Analysis to display the 0 - 5000 Hz frequency spectrum of signals saved 
% in the ScopeDataForFFT structure. The FFT will be performed on  a 2-cycle window starting at t = 0.07 - 2/60 (last 2 cycles of recording). 
% Click on Display and observe the frequency spectrum of last 2 cycles.
%
% The fundamental component of V inverter is displayed above the spectrum window.
% Compare the magnitude of the fundamental component of the inverter voltage with the theoretical values given in the circuit.
% Compare also the harmonic contents in the inverter voltage.
% 
% The half-bridge inverter generates a bipolar voltage (-200V or +200V).
% Harmonics occur around the carrier frequency (1620 Hz +- k*60 Hz), with a maximum of 103% at 1620 Hz.
% 
% The full-bridge inverter generates a monopolar voltage varying between 0 and +400V for one half cycle and then between 0 and -400V for the next half cycle.
% For the same DC voltage and modulation index, the fundamental component magnitude is twice the value obtained with the half-bridge. 
% Harmonics generated by the full-bridge are lower and they appear at twice the carrier frequency (maximum of 40% at 2*1620+-60 Hz).
% As a result, the current obtained with the full-bridge is smoother.  
%

%%

